export const seoKeywords = [
  'buy IPTV',
  'IPTV service',
  'best IPTV service',
  'IPTV subscription',
  'premium IPTV',
  'HD IPTV service',
  'streaming TV channels',
  'live TV streaming',
  '4K IPTV service',
  'affordable IPTV subscription',
  'USA IPTV service',
  'UK IPTV service',
  'worldwide IPTV',
  'IPTV provider',
  'streaming service',
  'live TV channels',
  'VOD service',
  'sports channels',
  'movie streaming',
  'TV shows streaming'
];