export const seoKeywords = [
  'iptv subscription',
  'best iptv',
  'iptv subscribe',
  'iptv providers',
  'iptv provider',
  'bestiptv',
  'iptv subscriptions',
  'iptv service',
  'iptv sub',
  'iptv suppliers',
  'buy iptv',
  'iptv services',
  'iptv',
  'premium iptv service',
  'HD IPTV service',
  'streaming TV channels',
  'live TV streaming',
  'USA IPTV service',
  'affordable IPTV subscription',
  '4K IPTV service',
  'IPTV provider USA',
  'best IPTV provider',
  'IPTV channels list',
  'sports IPTV service',
  'movies IPTV service',
  'iptv free trial',
  'iptv free trial reddit 2024',
  'iptv free trials',
  'free iptv trial',
  'free trial iptv',
  'iptv free trial 2024',
  'iptv with free trial',
  'free iptv trials',
  'free trial iptv service',
  'instant free iptv trial',
  'iptv service with free trial',
  'iptv service free trial',
  'best iptv free trials',
  'free trial of iptv'
];

export const getKeywordsString = () => seoKeywords.join(', ');