export interface PSEOVariationsTable {
  Row: {
    id: string;
    template_id: string | null;
    slug: string;
    title: string;
    description: string;
    h1: string;
    content: Json;
    keywords: string[];
    meta_tags: Json;
    structured_data: Json;
    is_indexed: boolean;
    priority: number;
    created_at: string;
    updated_at: string;
    social_tags: Json | null;
    schema_org: Json | null;
    last_indexed: string | null;
    indexing_status: string | null;
    page_type: string | null;
    locale: string | null;
    alternate_urls: Json | null;
    target_location: string | null;
    target_service_type: string | null;
    target_features: string[] | null;
    target_audience: string[] | null;
  };
  Insert: {
    id?: string;
    template_id?: string | null;
    slug: string;
    title: string;
    description: string;
    h1: string;
    content?: Json;
    keywords?: string[];
    meta_tags?: Json;
    structured_data?: Json;
    is_indexed?: boolean;
    priority?: number;
    created_at?: string;
    updated_at?: string;
    social_tags?: Json | null;
    schema_org?: Json | null;
    last_indexed?: string | null;
    indexing_status?: string | null;
    page_type?: string | null;
    locale?: string | null;
    alternate_urls?: Json | null;
    target_location?: string | null;
    target_service_type?: string | null;
    target_features?: string[] | null;
    target_audience?: string[] | null;
  };
  Update: {
    id?: string;
    template_id?: string | null;
    slug?: string;
    title?: string;
    description?: string;
    h1?: string;
    content?: Json;
    keywords?: string[];
    meta_tags?: Json;
    structured_data?: Json;
    is_indexed?: boolean;
    priority?: number;
    created_at?: string;
    updated_at?: string;
    social_tags?: Json | null;
    schema_org?: Json | null;
    last_indexed?: string | null;
    indexing_status?: string | null;
    page_type?: string | null;
    locale?: string | null;
    alternate_urls?: Json | null;
    target_location?: string | null;
    target_service_type?: string | null;
    target_features?: string[] | null;
    target_audience?: string[] | null;
  };
}