export interface SEOBulkPagesTable {
  Row: {
    id: string;
    slug: string;
    title: string;
    description: string;
    h1: string;
    content: Json;
    keywords: string[];
    meta_tags: Json;
    structured_data: Json;
    is_indexed: boolean;
    priority: number;
    created_at: string;
    updated_at: string;
    social_tags: Json | null;
    schema_org: Json | null;
    last_indexed: string | null;
    indexing_status: string | null;
    page_type: string | null;
    locale: string | null;
    alternate_urls: Json | null;
    target_location: string | null;
    target_service_type: string | null;
    target_features: string[] | null;
    target_audience: string[] | null;
    canonical_url: string | null;
    breadcrumbs: Json | null;
    faq_schema: Json | null;
    internal_links: Json | null;
    external_links: Json | null;
    image_alt_texts: Json | null;
    header_tags: Json | null;
    semantic_markup: string | null;
    word_count: number | null;
    keyword_density: Json | null;
  };
  Insert: {
    id?: string;
    slug: string;
    title: string;
    description: string;
    h1: string;
    content?: Json;
    keywords?: string[];
    meta_tags?: Json;
    structured_data?: Json;
    is_indexed?: boolean;
    priority?: number;
    created_at?: string;
    updated_at?: string;
    social_tags?: Json | null;
    schema_org?: Json | null;
    last_indexed?: string | null;
    indexing_status?: string | null;
    page_type?: string | null;
    locale?: string | null;
    alternate_urls?: Json | null;
    target_location?: string | null;
    target_service_type?: string | null;
    target_features?: string[] | null;
    target_audience?: string[] | null;
    canonical_url?: string | null;
    breadcrumbs?: Json | null;
    faq_schema?: Json | null;
    internal_links?: Json | null;
    external_links?: Json | null;
    image_alt_texts?: Json | null;
    header_tags?: Json | null;
    semantic_markup?: string | null;
    word_count?: number | null;
    keyword_density?: Json | null;
  };
  Update: {
    id?: string;
    slug?: string;
    title?: string;
    description?: string;
    h1?: string;
    content?: Json;
    keywords?: string[];
    meta_tags?: Json;
    structured_data?: Json;
    is_indexed?: boolean;
    priority?: number;
    created_at?: string;
    updated_at?: string;
    social_tags?: Json | null;
    schema_org?: Json | null;
    last_indexed?: string | null;
    indexing_status?: string | null;
    page_type?: string | null;
    locale?: string | null;
    alternate_urls?: Json | null;
    target_location?: string | null;
    target_service_type?: string | null;
    target_features?: string[] | null;
    target_audience?: string[] | null;
    canonical_url?: string | null;
    breadcrumbs?: Json | null;
    faq_schema?: Json | null;
    internal_links?: Json | null;
    external_links?: Json | null;
    image_alt_texts?: Json | null;
    header_tags?: Json | null;
    semantic_markup?: string | null;
    word_count?: number | null;
    keyword_density?: Json | null;
  };
}