// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzemomqyeyamurngohfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZW1vbXF5ZXlhbXVybmdvaGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1MzM4MTYsImV4cCI6MjA1MDEwOTgxNn0.ZuhR28hHhuFjXev2jWDRsZRAN5j9IbTRhyGnGm5uMuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);